/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.panosmatsinopoulos.coroutinecontextanddispatchers

import kotlinx.coroutines.*

@OptIn(ExperimentalCoroutinesApi::class, DelicateCoroutinesApi::class)
fun main() {
    runBlocking {
        launch {
            println("main runBlocking                             : I'm working in thread ${Thread.currentThread().name}")
            delay(1_000L)
            println("   main runBlocking                          : I'm working in thread ${Thread.currentThread().name}")
        }
        launch(Dispatchers.Unconfined) {
            println("main runBlocking unconfined                  : I'm working in thread ${Thread.currentThread().name}")
            delay(500L)
            println("   main runBlocking unconfined               : I'm working in thread ${Thread.currentThread().name}")
        }
        launch(Dispatchers.Default) {
            println("main runBlocking default                     : I'm working in thread ${Thread.currentThread().name}")
        }
        launch(newSingleThreadContext("MyOwnThread")) {
            println("main runBlocking newSingleThreadContext      : I'm working in thread ${Thread.currentThread().name}")
        }
    }
}
